name = "nvidia-tracker"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true

[[routes]]
pattern = "nvidia-tracker.seankel.com"
custom_domain = true
